import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next.js learning",
    template: `%s | Bahar`,
  },
  description: "Generated by Bahar Keshavarz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-[350]">
          <Link href="/products">Products</Link>
          <br />
          <br />
          <Link href="/about">about</Link>
          <br />
          <br />
          <Link href="/articles">articles</Link>
          <br />
          <br />
          <Link href="/server">server</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
